package mapreduce

import (
	"hash/fnv"
	"io/ioutil"
	"log"
	"math"
	"encoding/json"
	"os"
)

// doMap manages one map task: it reads one of the input files
// (inFile), calls the user-defined map function (mapF) for that file's
// contents, and partitions the output into nReduce intermediate files.
func doMap(
	jobName string, // the name of the MapReduce job
	mapTaskNumber int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(file string, contents string) []KeyValue,
) {

	// define intermediate file array, each element is a struct,
	// which saves a file pointer and a json encoder pointer
	var interFile []struct{
		file *os.File
		enc *json.Encoder
	}
	for i := 0; i < nReduce; i++ {
		// Find the corresponding intermediate file name
		fn := reduceName(jobName, mapTaskNumber, i)
		// Create the file pointer
		file, err := os.Create(fn)
		if err != nil {
			log.Println(err)
			return
		}
		// Create the json encoder pointer
		enc := json.NewEncoder(file)
		// Append the file pointer and encoder pointer into array
		interFile = append(interFile, struct {
			file *os.File
			enc  *json.Encoder
		}{ file: file, enc: enc })
	}

	// Read contents from inFile
	b, err := ioutil.ReadFile(inFile)
	if err != nil {
		log.Fatal(err)
	}

	// Get KeyValue from inFile by using mapF
	res := mapF(inFile, string(b))
	// Traverse the KeyValue
	for _, kv := range res {
		// Find the reduce number by using ihash and mod nReduce
		r := int(math.Mod(float64(ihash(kv.Key)), float64(nReduce)))
		// Encode the struct (KeyValue) into corresponding file
		// using json encoder
		err := interFile[r].enc.Encode(&kv)
		if err != nil {
			log.Println(err)
		}
	}
	// Close files in interFile array
	for i := range interFile {
		interFile[i].file.Close()
	}

	//
	// You will need to write this function.
	//
	// The intermediate output of a map task is stored as multiple
	// files, one per destination reduce task. The file name includes
	// both the map task number and the reduce task number. Use the
	// filename generated by reduceName(jobName, mapTaskNumber, r) as
	// the intermediate file for reduce task r. Call ihash() (see below)
	// on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	//
	// Look at Go's ioutil and os packages for functions to read
	// and write files.
	//
	// Coming up with a scheme for how to format the key/value pairs on
	// disk can be tricky, especially when taking into account that both
	// keys and values could contain newlines, quotes, and any other
	// character you can think of.
	//
	// One format often used for serializing data to a byte stream that the
	// other end can correctly reconstruct is JSON. You are not required to
	// use JSON, but as the output of the reduce tasks *must* be JSON,
	// familiarizing yourself with it here may prove useful. You can write
	// out a data structure as a JSON string to a file using the commented
	// code below. The corresponding decoding functions can be found in
	// common_reduce.go.
	//
	//   enc := json.NewEncoder(file)
	//   for _, kv := ... {
	//     err := enc.Encode(&kv)
	//
	// Remember to close the file after you have written all the values!
	//
}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}
